TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dma4500m.db
DB += dma4500m_error_setter.db
DATA += dma4500m.proto

#=======================================
include $(TOP)/configure/RULES
